name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on manylinux2014
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Delete existing wheels directory
      run: rm -rf wheels

    - name: Delete existing wheelhouse directory
      run: rm -rf wheelhouse

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_BUILD: cp*-manylinux_x86_64
        CIBW_BEFORE_BUILD: pip install -U pip
        CIBW_BUILD_VERBOSITY: 1

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: ./wheelhouse/ 