name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build_wheels:
    name: Build wheels on manylinux2014
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Delete existing wheels directory
      run: rm -rf wheelhouse

    - name: Build wheels in manylinux2014
      uses: addnab/docker-run-action@v3
      with:
        image: quay.io/pypa/manylinux2014_x86_64
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work
          /opt/python/cp39-cp39/bin/pip wheel --no-index --find-links wheels -w wheelhouse .

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheelhouse
        path: ./wheelhouse